// Code generated by protoc-gen-go.
// source: internal/pb/IM_BaseDefine/IM.BaseDefine.proto
// DO NOT EDIT!

/*
Package IM_BaseDefine is a generated protocol buffer package.

It is generated from these files:
	internal/pb/IM_BaseDefine/IM.BaseDefine.proto

It has these top-level messages:
*/
package IM_BaseDefine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// service id
type ServiceID int32

const (
	ServiceID_SID_UNUSED ServiceID = 0
	ServiceID_SID_LOGIN  ServiceID = 1
	ServiceID_SID_MSG    ServiceID = 3
	ServiceID_SID_OTHER  ServiceID = 7
)

var ServiceID_name = map[int32]string{
	0: "SID_UNUSED",
	1: "SID_LOGIN",
	3: "SID_MSG",
	7: "SID_OTHER",
}
var ServiceID_value = map[string]int32{
	"SID_UNUSED": 0,
	"SID_LOGIN":  1,
	"SID_MSG":    3,
	"SID_OTHER":  7,
}

func (x ServiceID) String() string {
	return proto.EnumName(ServiceID_name, int32(x))
}
func (ServiceID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// command id for login
type LoginCmdID int32

const (
	LoginCmdID_CID_LOGIN_UNUSED         LoginCmdID = 0
	LoginCmdID_CID_LOGIN_REQ_USERLOGIN  LoginCmdID = 259
	LoginCmdID_CID_LOGIN_RES_USERLOGIN  LoginCmdID = 260
	LoginCmdID_CID_LOGIN_REQ_USERLOGOUT LoginCmdID = 261
	LoginCmdID_CID_LOGIN_RES_USERLOGOUT LoginCmdID = 262
)

var LoginCmdID_name = map[int32]string{
	0:   "CID_LOGIN_UNUSED",
	259: "CID_LOGIN_REQ_USERLOGIN",
	260: "CID_LOGIN_RES_USERLOGIN",
	261: "CID_LOGIN_REQ_USERLOGOUT",
	262: "CID_LOGIN_RES_USERLOGOUT",
}
var LoginCmdID_value = map[string]int32{
	"CID_LOGIN_UNUSED":         0,
	"CID_LOGIN_REQ_USERLOGIN":  259,
	"CID_LOGIN_RES_USERLOGIN":  260,
	"CID_LOGIN_REQ_USERLOGOUT": 261,
	"CID_LOGIN_RES_USERLOGOUT": 262,
}

func (x LoginCmdID) String() string {
	return proto.EnumName(LoginCmdID_name, int32(x))
}
func (LoginCmdID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// command id for msg
type MessageCmdID int32

const (
	MessageCmdID_CID_MSG_UNUSED   MessageCmdID = 0
	MessageCmdID_CID_MSG_DATA     MessageCmdID = 769
	MessageCmdID_CID_MSG_DATA_ACK MessageCmdID = 770
)

var MessageCmdID_name = map[int32]string{
	0:   "CID_MSG_UNUSED",
	769: "CID_MSG_DATA",
	770: "CID_MSG_DATA_ACK",
}
var MessageCmdID_value = map[string]int32{
	"CID_MSG_UNUSED":   0,
	"CID_MSG_DATA":     769,
	"CID_MSG_DATA_ACK": 770,
}

func (x MessageCmdID) String() string {
	return proto.EnumName(MessageCmdID_name, int32(x))
}
func (MessageCmdID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type OtherCmdID int32

const (
	OtherCmdID_CID_OTHER_UNUSED           OtherCmdID = 0
	OtherCmdID_CID_OTHER_HEARTBEAT        OtherCmdID = 1793
	OtherCmdID_CID_OTHER_STOP_RECV_PACKET OtherCmdID = 1794
)

var OtherCmdID_name = map[int32]string{
	0:    "CID_OTHER_UNUSED",
	1793: "CID_OTHER_HEARTBEAT",
	1794: "CID_OTHER_STOP_RECV_PACKET",
}
var OtherCmdID_value = map[string]int32{
	"CID_OTHER_UNUSED":           0,
	"CID_OTHER_HEARTBEAT":        1793,
	"CID_OTHER_STOP_RECV_PACKET": 1794,
}

func (x OtherCmdID) String() string {
	return proto.EnumName(OtherCmdID_name, int32(x))
}
func (OtherCmdID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ResultType int32

const (
	ResultType_Ok      ResultType = 0
	ResultType_REFUSED ResultType = 1
)

var ResultType_name = map[int32]string{
	0: "Ok",
	1: "REFUSED",
}
var ResultType_value = map[string]int32{
	"Ok":      0,
	"REFUSED": 1,
}

func (x ResultType) String() string {
	return proto.EnumName(ResultType_name, int32(x))
}
func (ResultType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type UserStatType int32

const (
	UserStatType_USER_STATUS_UNKNOWN UserStatType = 0
	UserStatType_USER_STATUS_ONLINE  UserStatType = 1
	UserStatType_USER_STATUS_OFFLINE UserStatType = 2
	UserStatType_USER_STATUS_LEAVE   UserStatType = 3
	UserStatType_USER_STATUS_HIDDEN  UserStatType = 4
	UserStatType_USER_STATUS_BUSY    UserStatType = 5
)

var UserStatType_name = map[int32]string{
	0: "USER_STATUS_UNKNOWN",
	1: "USER_STATUS_ONLINE",
	2: "USER_STATUS_OFFLINE",
	3: "USER_STATUS_LEAVE",
	4: "USER_STATUS_HIDDEN",
	5: "USER_STATUS_BUSY",
}
var UserStatType_value = map[string]int32{
	"USER_STATUS_UNKNOWN": 0,
	"USER_STATUS_ONLINE":  1,
	"USER_STATUS_OFFLINE": 2,
	"USER_STATUS_LEAVE":   3,
	"USER_STATUS_HIDDEN":  4,
	"USER_STATUS_BUSY":    5,
}

func (x UserStatType) String() string {
	return proto.EnumName(UserStatType_name, int32(x))
}
func (UserStatType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ClientType int32

const (
	ClientType_CLIENT_TYPE_UNKNOWN   ClientType = 0
	ClientType_CLIENT_TYPE_ANDROID   ClientType = 1
	ClientType_CLIENT_TYPE_IOS       ClientType = 2
	ClientType_CLIENT_TYPE_WINDOWS   ClientType = 3
	ClientType_CLIENT_TYPE_MAC       ClientType = 4
	ClientType_CLIENT_TYPE_WEBIM     ClientType = 5
	ClientType_CLIENT_TYPE_IOS_WATCH ClientType = 6
)

var ClientType_name = map[int32]string{
	0: "CLIENT_TYPE_UNKNOWN",
	1: "CLIENT_TYPE_ANDROID",
	2: "CLIENT_TYPE_IOS",
	3: "CLIENT_TYPE_WINDOWS",
	4: "CLIENT_TYPE_MAC",
	5: "CLIENT_TYPE_WEBIM",
	6: "CLIENT_TYPE_IOS_WATCH",
}
var ClientType_value = map[string]int32{
	"CLIENT_TYPE_UNKNOWN":   0,
	"CLIENT_TYPE_ANDROID":   1,
	"CLIENT_TYPE_IOS":       2,
	"CLIENT_TYPE_WINDOWS":   3,
	"CLIENT_TYPE_MAC":       4,
	"CLIENT_TYPE_WEBIM":     5,
	"CLIENT_TYPE_IOS_WATCH": 6,
}

func (x ClientType) String() string {
	return proto.EnumName(ClientType_name, int32(x))
}
func (ClientType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterEnum("IM.BaseDefine.ServiceID", ServiceID_name, ServiceID_value)
	proto.RegisterEnum("IM.BaseDefine.LoginCmdID", LoginCmdID_name, LoginCmdID_value)
	proto.RegisterEnum("IM.BaseDefine.MessageCmdID", MessageCmdID_name, MessageCmdID_value)
	proto.RegisterEnum("IM.BaseDefine.OtherCmdID", OtherCmdID_name, OtherCmdID_value)
	proto.RegisterEnum("IM.BaseDefine.ResultType", ResultType_name, ResultType_value)
	proto.RegisterEnum("IM.BaseDefine.UserStatType", UserStatType_name, UserStatType_value)
	proto.RegisterEnum("IM.BaseDefine.ClientType", ClientType_name, ClientType_value)
}

func init() { proto.RegisterFile("internal/pb/IM_BaseDefine/IM.BaseDefine.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0xbf, 0xb8, 0x5f, 0x53, 0x71, 0x49, 0xc3, 0x74, 0x42, 0x69, 0x41, 0x20, 0xc4, 0xd6,
	0x12, 0xed, 0x82, 0x27, 0x98, 0xd8, 0x93, 0x66, 0x54, 0x7b, 0x26, 0x78, 0xc6, 0x8d, 0xba, 0x40,
	0x56, 0x0a, 0x43, 0xb1, 0x08, 0x4e, 0x64, 0x1b, 0x24, 0x96, 0x2d, 0x7f, 0x9e, 0x02, 0x9e, 0x82,
	0x17, 0xe4, 0x26, 0x56, 0xb0, 0x63, 0x58, 0xde, 0xf3, 0xbb, 0xf7, 0xe8, 0x1c, 0x4f, 0x02, 0xcf,
	0xd3, 0xac, 0xb4, 0x79, 0x36, 0x9b, 0x9f, 0x2e, 0xaf, 0x4e, 0x45, 0x98, 0x0c, 0x67, 0x85, 0xf5,
	0xed, 0xdb, 0x34, 0xb3, 0x38, 0x9d, 0xd4, 0xd3, 0xc9, 0x32, 0x5f, 0x94, 0x0b, 0xba, 0xbf, 0x25,
	0xba, 0x23, 0xb8, 0xa3, 0x6d, 0xfe, 0x29, 0x7d, 0x6d, 0x85, 0x4f, 0xfb, 0x00, 0x5a, 0xf8, 0x49,
	0x2c, 0x63, 0xcd, 0x7d, 0xf2, 0x1f, 0xdd, 0x47, 0x88, 0x73, 0xa0, 0xce, 0x84, 0x24, 0x1d, 0x7a,
	0x17, 0xf6, 0x56, 0x63, 0xa8, 0xcf, 0xc8, 0xce, 0x86, 0x29, 0x33, 0xe6, 0x11, 0xd9, 0x73, 0x7f,
	0x74, 0x00, 0x82, 0xc5, 0x75, 0x9a, 0x79, 0x1f, 0xde, 0xa0, 0xd3, 0x7d, 0x20, 0xde, 0xe6, 0xb2,
	0xf6, 0x7b, 0x0c, 0x47, 0xb5, 0x1a, 0xf1, 0x97, 0x09, 0xea, 0x51, 0xe5, 0xfe, 0xc5, 0x69, 0x53,
	0xdd, 0xa0, 0x5f, 0x1d, 0xfa, 0x04, 0x8e, 0xff, 0x79, 0xab, 0x62, 0x43, 0xbe, 0xfd, 0x85, 0x75,
	0x13, 0x7f, 0x77, 0xdc, 0x00, 0x7a, 0xa1, 0x2d, 0x8a, 0xd9, 0xb5, 0xad, 0xf2, 0x51, 0xe8, 0x7b,
	0x55, 0x95, 0x3a, 0xdd, 0x01, 0xf4, 0x36, 0x9a, 0xcf, 0x0c, 0x23, 0x37, 0x5d, 0x7a, 0x58, 0xd5,
	0xd8, 0x48, 0x09, 0xf3, 0xce, 0xc9, 0x6d, 0xd7, 0x7d, 0x05, 0xa0, 0xca, 0x77, 0x36, 0xdf, 0xea,
	0xba, 0xfe, 0x12, 0xb5, 0xdb, 0x31, 0x0c, 0x6a, 0x75, 0xcc, 0x59, 0x64, 0x86, 0x9c, 0x19, 0x72,
	0xd3, 0xa7, 0x4f, 0xe1, 0x51, 0x4d, 0xb4, 0x51, 0x13, 0xcc, 0xeb, 0x5d, 0x24, 0x13, 0x34, 0xe7,
	0x86, 0xdc, 0xf6, 0xdd, 0x67, 0x00, 0x91, 0x2d, 0x3e, 0xce, 0x4b, 0xf3, 0x79, 0x69, 0x69, 0x17,
	0x1c, 0xf5, 0x1e, 0x0d, 0xf1, 0xeb, 0x47, 0x7c, 0xb4, 0x76, 0xef, 0xb8, 0x3f, 0x3b, 0xd0, 0x8b,
	0x0b, 0x9b, 0xeb, 0x72, 0x56, 0x6d, 0x1d, 0xc1, 0x60, 0xd5, 0x18, 0xfd, 0x98, 0x89, 0xb1, 0xbd,
	0x3c, 0x97, 0x6a, 0x2a, 0xf1, 0xec, 0x01, 0xd0, 0x26, 0x50, 0x32, 0x10, 0x92, 0xe3, 0x63, 0xb6,
	0x0e, 0xd4, 0x68, 0xb4, 0x06, 0x0e, 0x76, 0x3e, 0x68, 0x82, 0x80, 0xb3, 0x0b, 0x8e, 0xef, 0xdd,
	0xf2, 0x19, 0x0b, 0xdf, 0xe7, 0x92, 0xfc, 0xbf, 0x6a, 0xdf, 0xd4, 0x87, 0xb1, 0xbe, 0x24, 0xbb,
	0xee, 0x2f, 0xfc, 0x39, 0x78, 0xf3, 0xd4, 0x66, 0x7f, 0xd2, 0x79, 0x81, 0xe0, 0xd2, 0x24, 0xe6,
	0x72, 0xc2, 0x1b, 0xe9, 0x5a, 0x80, 0x49, 0x3f, 0x52, 0x02, 0x0b, 0xd2, 0x01, 0xdc, 0x6b, 0x02,
	0xa1, 0x34, 0x46, 0x6b, 0x6d, 0x4f, 0x85, 0xf4, 0xd5, 0x54, 0x63, 0xb8, 0xd6, 0x76, 0xc8, 0x3c,
	0x4c, 0x86, 0x45, 0xb6, 0xb6, 0xf9, 0x50, 0x84, 0x64, 0x97, 0x3e, 0x84, 0xc3, 0x96, 0x73, 0x32,
	0x65, 0xc6, 0x1b, 0x93, 0xee, 0xd0, 0x19, 0xef, 0x5c, 0x75, 0xd7, 0x7f, 0x93, 0x17, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x42, 0x95, 0x19, 0xdb, 0x57, 0x03, 0x00, 0x00,
}
