// Code generated by protoc-gen-go.
// source: tuohai/internal/pb/MsgSrv/MsgSrv.proto
// DO NOT EDIT!

/*
Package MsgSrv is a generated protocol buffer package.

It is generated from these files:
	tuohai/internal/pb/MsgSrv/MsgSrv.proto

It has these top-level messages:
	SendNotifyReq
	SendRst
*/
package MsgSrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_Message "tuohai/internal/pb/IM_Message"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotifyType int32

const (
	NotifyType_NOTIFY_TYPE_KICK_CLIENT  NotifyType = 0
	NotifyType_NOTIFY_TYPE_READ_ACK     NotifyType = 1
	NotifyType_NOTIFY_TYPE_GROUP_NOTIFY NotifyType = 2
)

var NotifyType_name = map[int32]string{
	0: "NOTIFY_TYPE_KICK_CLIENT",
	1: "NOTIFY_TYPE_READ_ACK",
	2: "NOTIFY_TYPE_GROUP_NOTIFY",
}
var NotifyType_value = map[string]int32{
	"NOTIFY_TYPE_KICK_CLIENT":  0,
	"NOTIFY_TYPE_READ_ACK":     1,
	"NOTIFY_TYPE_GROUP_NOTIFY": 2,
}

func (x NotifyType) String() string {
	return proto.EnumName(NotifyType_name, int32(x))
}
func (NotifyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SendNotifyReq struct {
	NotifyType NotifyType `protobuf:"varint,1,opt,name=notify_type,json=notifyType,enum=MsgSrv.NotifyType" json:"notify_type,omitempty"`
	Content    string     `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	RcvId      string     `protobuf:"bytes,3,opt,name=rcv_id,json=rcvId" json:"rcv_id,omitempty"`
}

func (m *SendNotifyReq) Reset()                    { *m = SendNotifyReq{} }
func (m *SendNotifyReq) String() string            { return proto.CompactTextString(m) }
func (*SendNotifyReq) ProtoMessage()               {}
func (*SendNotifyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SendRst struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *SendRst) Reset()                    { *m = SendRst{} }
func (m *SendRst) String() string            { return proto.CompactTextString(m) }
func (*SendRst) ProtoMessage()               {}
func (*SendRst) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SendNotifyReq)(nil), "MsgSrv.SendNotifyReq")
	proto.RegisterType((*SendRst)(nil), "MsgSrv.SendRst")
	proto.RegisterEnum("MsgSrv.NotifyType", NotifyType_name, NotifyType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MsgLogic service

type MsgLogicClient interface {
	// msg process logic
	SendMsg(ctx context.Context, in *IM_Message.IMMsgData, opts ...grpc.CallOption) (*IM_Message.IMMsgDataAck, error)
	DispatchMsg(ctx context.Context, in *IM_Message.IMMsgData, opts ...grpc.CallOption) (*SendRst, error)
	DispatchNotify(ctx context.Context, in *SendNotifyReq, opts ...grpc.CallOption) (*SendRst, error)
}

type msgLogicClient struct {
	cc *grpc.ClientConn
}

func NewMsgLogicClient(cc *grpc.ClientConn) MsgLogicClient {
	return &msgLogicClient{cc}
}

func (c *msgLogicClient) SendMsg(ctx context.Context, in *IM_Message.IMMsgData, opts ...grpc.CallOption) (*IM_Message.IMMsgDataAck, error) {
	out := new(IM_Message.IMMsgDataAck)
	err := grpc.Invoke(ctx, "/MsgSrv.MsgLogic/SendMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgLogicClient) DispatchMsg(ctx context.Context, in *IM_Message.IMMsgData, opts ...grpc.CallOption) (*SendRst, error) {
	out := new(SendRst)
	err := grpc.Invoke(ctx, "/MsgSrv.MsgLogic/DispatchMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgLogicClient) DispatchNotify(ctx context.Context, in *SendNotifyReq, opts ...grpc.CallOption) (*SendRst, error) {
	out := new(SendRst)
	err := grpc.Invoke(ctx, "/MsgSrv.MsgLogic/DispatchNotify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MsgLogic service

type MsgLogicServer interface {
	// msg process logic
	SendMsg(context.Context, *IM_Message.IMMsgData) (*IM_Message.IMMsgDataAck, error)
	DispatchMsg(context.Context, *IM_Message.IMMsgData) (*SendRst, error)
	DispatchNotify(context.Context, *SendNotifyReq) (*SendRst, error)
}

func RegisterMsgLogicServer(s *grpc.Server, srv MsgLogicServer) {
	s.RegisterService(&_MsgLogic_serviceDesc, srv)
}

func _MsgLogic_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IM_Message.IMMsgData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgLogicServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MsgSrv.MsgLogic/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgLogicServer).SendMsg(ctx, req.(*IM_Message.IMMsgData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgLogic_DispatchMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IM_Message.IMMsgData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgLogicServer).DispatchMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MsgSrv.MsgLogic/DispatchMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgLogicServer).DispatchMsg(ctx, req.(*IM_Message.IMMsgData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgLogic_DispatchNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgLogicServer).DispatchNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MsgSrv.MsgLogic/DispatchNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgLogicServer).DispatchNotify(ctx, req.(*SendNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgLogic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MsgSrv.MsgLogic",
	HandlerType: (*MsgLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _MsgLogic_SendMsg_Handler,
		},
		{
			MethodName: "DispatchMsg",
			Handler:    _MsgLogic_DispatchMsg_Handler,
		},
		{
			MethodName: "DispatchNotify",
			Handler:    _MsgLogic_DispatchNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for MsgSender service

type MsgSenderClient interface {
	// send to reciever
	SendTo(ctx context.Context, in *IM_Message.IMMsgData, opts ...grpc.CallOption) (*SendRst, error)
}

type msgSenderClient struct {
	cc *grpc.ClientConn
}

func NewMsgSenderClient(cc *grpc.ClientConn) MsgSenderClient {
	return &msgSenderClient{cc}
}

func (c *msgSenderClient) SendTo(ctx context.Context, in *IM_Message.IMMsgData, opts ...grpc.CallOption) (*SendRst, error) {
	out := new(SendRst)
	err := grpc.Invoke(ctx, "/MsgSrv.MsgSender/SendTo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MsgSender service

type MsgSenderServer interface {
	// send to reciever
	SendTo(context.Context, *IM_Message.IMMsgData) (*SendRst, error)
}

func RegisterMsgSenderServer(s *grpc.Server, srv MsgSenderServer) {
	s.RegisterService(&_MsgSender_serviceDesc, srv)
}

func _MsgSender_SendTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IM_Message.IMMsgData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgSenderServer).SendTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MsgSrv.MsgSender/SendTo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgSenderServer).SendTo(ctx, req.(*IM_Message.IMMsgData))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgSender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MsgSrv.MsgSender",
	HandlerType: (*MsgSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTo",
			Handler:    _MsgSender_SendTo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for Nofifier service

type NofifierClient interface {
	SendNotify(ctx context.Context, in *SendNotifyReq, opts ...grpc.CallOption) (*SendRst, error)
}

type nofifierClient struct {
	cc *grpc.ClientConn
}

func NewNofifierClient(cc *grpc.ClientConn) NofifierClient {
	return &nofifierClient{cc}
}

func (c *nofifierClient) SendNotify(ctx context.Context, in *SendNotifyReq, opts ...grpc.CallOption) (*SendRst, error) {
	out := new(SendRst)
	err := grpc.Invoke(ctx, "/MsgSrv.Nofifier/SendNotify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Nofifier service

type NofifierServer interface {
	SendNotify(context.Context, *SendNotifyReq) (*SendRst, error)
}

func RegisterNofifierServer(s *grpc.Server, srv NofifierServer) {
	s.RegisterService(&_Nofifier_serviceDesc, srv)
}

func _Nofifier_SendNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NofifierServer).SendNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MsgSrv.Nofifier/SendNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NofifierServer).SendNotify(ctx, req.(*SendNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nofifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MsgSrv.Nofifier",
	HandlerType: (*NofifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotify",
			Handler:    _Nofifier_SendNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("tuohai/internal/pb/MsgSrv/MsgSrv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6b, 0xea, 0x40,
	0x14, 0x35, 0xfa, 0x8c, 0x7a, 0xe5, 0xf9, 0xc2, 0xf0, 0xa4, 0xc1, 0x16, 0x5a, 0xdc, 0xb4, 0x74,
	0x11, 0x21, 0x42, 0x0b, 0xa5, 0x50, 0xfc, 0x6a, 0x1b, 0x34, 0x51, 0x62, 0xba, 0x70, 0x35, 0xc4,
	0x24, 0xa6, 0xa1, 0x6d, 0x26, 0x4d, 0xa6, 0x82, 0x3f, 0xae, 0xff, 0xad, 0x93, 0x0f, 0x35, 0x0b,
	0x29, 0xae, 0x72, 0xce, 0x3d, 0xf7, 0xcc, 0xb9, 0x73, 0x33, 0x70, 0xee, 0xf9, 0xd4, 0x09, 0x7d,
	0xf3, 0xbd, 0x13, 0x2c, 0x3b, 0x6a, 0xe4, 0xce, 0xc3, 0x75, 0xf6, 0x91, 0x82, 0x90, 0x50, 0x82,
	0xf8, 0x94, 0xb5, 0x2e, 0xf3, 0x8d, 0x8a, 0x8a, 0x55, 0x27, 0x8a, 0x4c, 0xd7, 0x61, 0x50, 0xca,
	0x60, 0x6a, 0x68, 0x7f, 0xc1, 0xdf, 0xb9, 0xe3, 0xdb, 0x1a, 0xa1, 0xde, 0x6a, 0xa3, 0x3b, 0x9f,
	0xa8, 0x0b, 0x75, 0x3f, 0x21, 0x98, 0x6e, 0x02, 0x47, 0xe4, 0x2e, 0xb8, 0xab, 0x86, 0x8c, 0xa4,
	0x2c, 0x25, 0xed, 0x33, 0x98, 0xa2, 0x83, 0xbf, 0xc3, 0x48, 0x84, 0x8a, 0x45, 0x58, 0xa2, 0x4f,
	0xc5, 0x22, 0x33, 0xd4, 0xf4, 0x2d, 0x45, 0x4d, 0xe0, 0x43, 0x6b, 0x8d, 0x3d, 0x5b, 0x2c, 0x25,
	0x42, 0x99, 0x31, 0xc5, 0x6e, 0x77, 0xa0, 0x12, 0xc7, 0xea, 0x11, 0x45, 0x08, 0xfe, 0x58, 0xc4,
	0x4e, 0x93, 0xca, 0x7a, 0x82, 0x91, 0x00, 0xa5, 0x8f, 0xc8, 0xcd, 0xce, 0x8a, 0xe1, 0xb5, 0x09,
	0xb0, 0xcf, 0x46, 0xa7, 0x70, 0xa2, 0x4d, 0x0d, 0xe5, 0x71, 0x81, 0x8d, 0xc5, 0x6c, 0x84, 0xc7,
	0xca, 0x60, 0x8c, 0x07, 0x13, 0x65, 0xa4, 0x19, 0x42, 0x81, 0x0d, 0xf3, 0x3f, 0x2f, 0xea, 0xa3,
	0xde, 0x10, 0xf7, 0x06, 0x63, 0x81, 0x43, 0x67, 0x20, 0xe6, 0x95, 0x27, 0x7d, 0xfa, 0x32, 0xc3,
	0x69, 0x45, 0x28, 0xca, 0xdf, 0x1c, 0x54, 0xd9, 0x35, 0x27, 0xc4, 0xf5, 0x2c, 0x74, 0x9f, 0x0e,
	0xc8, 0x38, 0x6a, 0x4a, 0xb9, 0xad, 0x29, 0x2a, 0x2b, 0x0d, 0x4d, 0x6a, 0xb6, 0xc4, 0x83, 0xe5,
	0x9e, 0xf5, 0xd6, 0x2e, 0xa0, 0x5b, 0xa8, 0x0f, 0xbd, 0x28, 0x30, 0xa9, 0xf5, 0xfa, 0xcb, 0x09,
	0xff, 0xb6, 0x5b, 0xcd, 0x56, 0xc1, 0x8c, 0x77, 0xd0, 0xd8, 0x1a, 0xd3, 0xeb, 0x32, 0x6f, 0xae,
	0x69, 0xf7, 0x9b, 0x0e, 0x78, 0xe5, 0x07, 0xa8, 0xc5, 0x35, 0xc6, 0x9d, 0x10, 0xc9, 0xc0, 0xc7,
	0xc8, 0x20, 0xc7, 0x87, 0xcb, 0x7d, 0xa8, 0x6a, 0x64, 0xe5, 0xad, 0x3c, 0xe6, 0xbf, 0x01, 0xd8,
	0x07, 0x1e, 0x3f, 0x44, 0xbf, 0xf8, 0x5c, 0x5a, 0xf2, 0xc9, 0xd3, 0xea, 0xfe, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xa5, 0x6e, 0x6b, 0x3d, 0xae, 0x02, 0x00, 0x00,
}
